return {
  "ellisonleao/carbon-now.nvim",
  keys = { { "<A-Space>n", vim.cmd.CarbonNow, mode = "v", desc = "Carbon Now" } },
  cmd = "CarbonNow",
  opts = {
    base_url = "https://carbon.now.sh/",
    options = {
      bg = "gray",
      drop_shadow_blur = "68px",
      drop_shadow = false,
      drop_shadow_offset_y = "20px",
      font_family = "JetBrains Mono",
      font_size = "18px",
      line_height = "133%",
      line_numbers = true,
      theme = "nord",
      titlebar = "Made with carbon-now.nvim",
      watermark = false,
      width = "1280",
      window_theme = "rounded",
      padding_horizontal = "0px",
      padding_vertical = "0px",
    },
  },
}
